# Generated by Django 3.0.3 on 2020-08-28 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='app_number',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='door_number',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psychologue',
            name='permis_date',
            field=models.DateField(blank=True, default='2018-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='psychologue',
            name='permis_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
