# Generated by Django 3.0.3 on 2020-08-29 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200828_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_client',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_psychologist',
        ),
    ]
