# Generated by Django 3.0.3 on 2020-08-29 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200828_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_client',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='client',
            name='is_psychologist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='psychologue',
            name='is_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='psychologue',
            name='is_psychologist',
            field=models.BooleanField(default=True),
        ),
    ]
