# Generated by Django 3.0.3 on 2020-08-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200828_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychologue',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile_picture/'),
        ),
    ]
