# Generated by Django 3.0.3 on 2020-09-01 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200829_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='psychologue_traitant',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='users.Psychologue'),
            preserve_default=False,
        ),
    ]
