# Generated by Django 3.0.3 on 2020-09-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_client_psychologue_traitant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='psychologue',
            options={'verbose_name': 'Psychologue', 'verbose_name_plural': 'Psychologues'},
        ),
        migrations.AlterField(
            model_name='psychologue',
            name='avatar',
            field=models.ImageField(upload_to='media/profile_picture/'),
        ),
    ]
