# Generated by Django 3.0.3 on 2020-09-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200903_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='app_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
