# Generated by Django 3.0.3 on 2020-09-03 22:07

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200903_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conferencier',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('education', models.CharField(blank=True, max_length=70)),
                ('site_web', models.URLField(blank=True)),
                ('linked_in', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Conférencier',
                'verbose_name_plural': 'Conférenciers',
            },
            bases=('users.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
