# Generated by Django 3.0.3 on 2020-09-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200909_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychologue',
            name='permis_num',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
