# Generated by Django 3.0.3 on 2020-09-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200911_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologue',
            name='tps',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='psychologue',
            name='tvq',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
