# Generated by Django 3.0.3 on 2020-09-28 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200915_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_male',
            field=models.BooleanField(default=False),
        ),
    ]
