# Generated by Django 3.0.3 on 2020-09-03 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0003_auto_20200903_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturable',
            name='facture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='facture.Facture'),
            preserve_default=False,
        ),
    ]
