# Generated by Django 3.0.3 on 2020-09-14 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0008_auto_20200914_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestationdeservice',
            name='qte',
        ),
    ]
