# Generated by Django 3.0.3 on 2020-09-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0009_remove_prestationdeservice_qte'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestationdeservice',
            name='qte',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
