# Generated by Django 3.0.3 on 2020-09-17 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0010_prestationdeservice_qte'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facture',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='prestationdeservice',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='facture',
            name='status',
        ),
        migrations.AddField(
            model_name='facture',
            name='close_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='status_facture',
            field=models.BooleanField(default=True),
        ),
    ]
