# Generated by Django 3.0.3 on 2020-09-21 20:16

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0011_auto_20200917_1942'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='prestationdeservice',
            managers=[
                ('sous_total', django.db.models.manager.Manager()),
            ],
        ),
    ]
