# Generated by Django 3.0.3 on 2020-09-21 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0012_auto_20200921_1616'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='prestationdeservice',
            managers=[
            ],
        ),
    ]
