# Generated by Django 3.0.3 on 2020-09-23 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0013_auto_20200921_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facture',
            old_name='status_facture',
            new_name='is_active',
        ),
    ]
