# Generated by Django 3.0.3 on 2020-09-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='desc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
