# Generated by Django 3.0.3 on 2020-09-11 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200909_1356'),
        ('service', '0002_service_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='psy',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, to='users.Psychologue'),
            preserve_default=False,
        ),
    ]
