# Generated by Django 3.0.3 on 2020-09-11 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_service_psy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='psy',
            new_name='psychologue',
        ),
    ]
