# Generated by Django 3.0.3 on 2020-09-11 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20200911_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='desc',
            new_name='description',
        ),
    ]
