# Generated by Django 3.0.3 on 2020-09-16 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200915_0827'),
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notetype',
            name='psychologue',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, to='users.Psychologue'),
            preserve_default=False,
        ),
    ]
