# Generated by Django 3.0.3 on 2020-09-17 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_notetype_psychologue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
