# Generated by Django 3.0.3 on 2020-09-22 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_auto_20200911_1232'),
        ('note', '0003_auto_20200916_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service.Service'),
            preserve_default=False,
        ),
    ]
