# Generated by Django 3.0.3 on 2020-09-15 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200915_0827'),
        ('documents', '0003_documenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='documents.DocumentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documenttype',
            name='psychologue',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, to='users.Psychologue'),
            preserve_default=False,
        ),
    ]
