# Generated by Django 3.0.3 on 2020-09-15 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20200915_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documenttype',
            old_name='name',
            new_name='nom',
        ),
    ]
