# Generated by Django 3.0.3 on 2020-09-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_document_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_extention',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
