# Generated by Django 3.0.3 on 2020-09-03 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0009_conferencier'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementCV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('psychologue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Psychologue')),
            ],
        ),
        migrations.CreateModel(
            name='AssociationProfessionelle',
            fields=[
                ('elementcv_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='curriculum_vitae.ElementCV')),
                ('permis', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('status', models.BooleanField(default=False)),
            ],
            bases=('curriculum_vitae.elementcv',),
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('elementcv_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='curriculum_vitae.ElementCV')),
                ('date', models.DateField()),
                ('organisme', models.CharField(max_length=200)),
                ('titre', models.CharField(max_length=200)),
                ('lieu', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
            ],
            bases=('curriculum_vitae.elementcv',),
        ),
        migrations.CreateModel(
            name='CorporationProfessionelle',
            fields=[
                ('elementcv_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='curriculum_vitae.ElementCV')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('description', models.CharField(max_length=200)),
            ],
            bases=('curriculum_vitae.elementcv',),
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('elementcv_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='curriculum_vitae.ElementCV')),
                ('institution', models.CharField(max_length=200)),
                ('date_obtention', models.DateField()),
                ('type', models.CharField(choices=[('CR', 'Certification'), ('FC', 'Formation Continue')], default='FC', max_length=2)),
            ],
            bases=('curriculum_vitae.elementcv',),
        ),
        migrations.CreateModel(
            name='ExpérienceProfessionelle',
            fields=[
                ('elementcv_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='curriculum_vitae.ElementCV')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('description', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('ET', 'expériences de travail'), ('AA', 'activité academique'), ('CP', 'corporations ou sociétés professionnelle')], default='ET', max_length=2)),
            ],
            bases=('curriculum_vitae.elementcv',),
        ),
    ]
