# Generated by Django 3.0.3 on 2020-09-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum_vitae', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporationprofessionelle',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
