# Generated by Django 3.0.3 on 2020-09-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum_vitae', '0003_auto_20200904_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='formateur',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
