# Generated by Django 3.0.3 on 2020-09-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum_vitae', '0005_auto_20200904_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='formateur_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='institute_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
