# Generated by Django 3.0.3 on 2020-09-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum_vitae', '0006_auto_20200904_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementcv',
            name='nom',
            field=models.CharField(max_length=500),
        ),
    ]
