# Generated by Django 3.0.3 on 2020-09-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum_vitae', '0007_auto_20200908_0828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='associationprofessionelle',
            old_name='date',
            new_name='date_debut',
        ),
        migrations.AddField(
            model_name='associationprofessionelle',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
