# Generated by Django 3.0.3 on 2020-09-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum_vitae', '0008_auto_20200910_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associationprofessionelle',
            name='date_debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='associationprofessionelle',
            name='permis',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
