# Generated by Django 3.0.3 on 2020-09-10 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum_vitae', '0009_auto_20200910_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='associationprofessionelle',
            name='status',
        ),
    ]
